version: '3.8'

services:
  voice-chat-app:
    build: .
    container_name: voice-chat-llm
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: on-failure:5
    volumes:
      - uploads:/app/public/uploads
      - logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - app-network

volumes:
  uploads:
  logs:

networks:
  app-network: